name: Auto release on merge

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**
      - "**/*.md"
      - .gitignore
      - .pre-commit-config.yaml
      - .tflint.hcl
      - LICENSE
      - renovate.json
      - examples/**
      - scripts/**
      - tests/**

jobs:
  auto-release:
    uses: dfds/shared-workflows/.github/workflows/automation-auto-release.yml@v2.0.1

  dispatch-blueprints:
    needs: auto-release
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to blueprints
        run: |
          curl -X POST https://api.github.com/repos/dfds/infrastructure-blueprints/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.AUTH_TOKEN }} \
          --data '{"event_type": "trigger-ssm-agent-workflow", "client_payload": { "release_tag": "${{ needs.auto-release.outputs.tag_name }}" }}'
